### ISSUE TITLE
Device /dev/sdb doesn't exist

### ISSUE THREAD

**Issue by rafabene** [oracle-samples/oltrain#17]
When running the command `sudo heketi-cli --user admin --secret "admin" topology load --json=/etc/heketi/topology.json`

it replies

> 	Found node worker1.vagrant.vm on cluster bfcfe3588dd26a01e8c41035acace144
		Adding device /dev/sdb ... Unable to add device: **Device /dev/sdb not found.**
	Found node worker2.vagrant.vm on cluster bfcfe3588dd26a01e8c41035acace144
		Adding device /dev/sdb ... Unable to add device: **Device /dev/sdb not found.**
	Found node worker3.vagrant.vm on cluster bfcfe3588dd26a01e8c41035acace144
		Adding device /dev/sdb ... Unable to add device: **Device /dev/sdb not found.**

**Comment by bgraef** [comment]
Closing as this repository has been repurposed and labs moved to Luna
